### ISSUE TITLE
Internal PTS/DTS resync UNEXPECTED EXCEPTION

### ISSUE THREAD

**Issue by Lowclock** [cabernetwork/provider_video_plutotv#1] opened 2024-05-06 08:19 UTC
I have attached a config.ini and a debug mode log. It doesn't matter what channel I try to open, or what client I use to open it. VLC, Kodi, Jellyfin, TVheadend's player, m3u, hdhr, windows, linux, docker, they all produce this error and no playback.

Is there any chance the internal resync mode could help with getting PlutoTV to behave properly with commercials? I've gotten pretty close to making it usable with different settings, but I always end up with either long pauses or complete desyncs that cause audio only, the connection to close, or some ailment that eventually means I have to re-open the channel. Threadfin behaves similarly, and Kodi has a PlutoTV plug-in that handles commercials flawlessly, but causes other problems.

[cabernet - Copy.log](https://github.com/cabernetwork/cabernet/files/15218310/cabernet.-.Copy.log)
[config - Copy.txt](https://github.com/cabernetwork/cabernet/files/15218317/config.-.Copy.txt)

**Comment by rocky4546** [comment] 2024-05-06 13:55
I will take a look at handling the exception better, but the issue is that ffmpeg is not starting correctly.  I would check your system.

As for plutotv.  ffmpeg does not handle the dts/pts variances with the commercials to the main stream correctly, so no the resync will not fix it.  The only way to fix plutotv is to remove the commercials using the filter.

**Comment by Lowclock** [comment] 2024-05-06 16:55
On both windows and linux I've tried ffmpeg 7.0 or 6.11 in my path that function fine with everything I've tried, and also even pip installed ffmpeg, ffprobe, ffmpeg-python, python-ffmpeg, or anything else I could find. I even get the same error with the docker image that already comes with ffmpeg in what I presume should be a usable state, and also every pip or apk I can find there as well with no change at all. What could I possibly be missing?

**Comment by redredkrovy** [comment] 2024-05-23 00:08
> I will take a look at handling the exception better, but the issue is that ffmpeg is not starting correctly. I would check your system.
> 
> As for plutotv. ffmpeg does not handle the dts/pts variances with the commercials to the main stream correctly, so no the resync will not fix it. The only way to fix plutotv is to remove the commercials using the filter.

Which filter do you speak of?  URL Filtering in the settings editor for PlutoTV?  If so what value do I put there to filter the commercials?  I'm getting stuttering on my Jellyfin server when viewing PlutoTV.  Trying to solve it.  From what I understand it has to do with the commercials causing some desync with time stamps.

Edit: I think I figured it out.  I enabled URL Filtering under PlutoTV and there were already entries in the URL Filter section.  Still didn't work for the commercials unfortunately though.  They still freeze the stream and I get an error about the non-monotonous DTS whatever.

**Comment by rocky4546** [comment] 2024-05-23 19:15
url filter setting in cabernet for plutotv.

If you find commercials are still coming through, you can update the filter to remove those. Check the log at the INFO level to see the data filtered and streamed.  It is normally obvious when it is a commercial.

One other note on pluto.  I found non-live channels can have different DTS/PTS for each thing it plays.  Example is Star Trek. Cabernet has a micro adjustment to the second for start and stop, so that, you can start the show just after it starts and ends before it ends giving you a clean copy.  The sensitivity is normally 6 seconds.  You can also create multiple instances and have each instance have different micro adjustments since channels never use the same clock for some reason.

**Comment by noideaman** [comment] 2024-07-13 22:34
I am having the same issue, it seems like it has been awhile as any progress been made?

**Comment by rocky4546** [comment] 2024-07-13 23:05
Until information is provided, the issue cannot be addressed.  The most important piece is to provide an INFO level log during the stream including when it is suppose to filter out the ads.  It should be obvious if there are additional URLs that should be filtered and are not.

**Comment by rocky4546** [comment] 2024-12-03 23:19
I have determined the issue is the DTS/PTS data from the provider is so corrupted that ffmpeg is failing with an error to resync the data.  The answer is to not have PTS Resync enabled.  I have changed the default to False and made a few changes to help when running live streaming instead of recordings.  It all looks like it plays well at this point.  Closing issue.

**Closed as completed by rocky4546** 2024-12-03 23:19 UTC
